In [ ]:
import numpy as np
#RANDOM MODULE IS SUB-PACKAGE OF NUMPY

In [ ]:
A=np.random.rand(1)
print(A)

[0.1935133]


In [ ]:
A=np.random.rand(8,4) #rand-range is between 0 and 1
print(A)

[[0.5213426  0.73753633 0.81314887 0.88876407]
 [0.65729283 0.06865491 0.22537853 0.26281232]
 [0.57060838 0.89847752 0.97979201 0.09542879]
 [0.97650772 0.06384882 0.55533023 0.37983965]
 [0.00765257 0.35116485 0.10123379 0.38366172]
 [0.98709374 0.22189798 0.44073188 0.80792289]
 [0.14715433 0.84988534 0.49921381 0.19628431]
 [0.43418363 0.67817619 0.32002949 0.60115376]]


In [ ]:
A=10*np.random.rand(8,4)
print(A)

[[6.37740433 6.36013597 5.10373505 3.45926623]
 [7.5040893  6.00283979 3.11418381 5.84073943]
 [0.79323541 2.20072868 2.80764375 9.11156707]
 [4.68152818 4.26977255 4.33209042 5.81817987]
 [5.0758334  2.69499938 9.08402632 3.68892008]
 [0.59711622 4.46811777 4.19112517 2.84406124]
 [4.90584147 2.18911543 3.2234673  3.97792875]
 [6.3314008  9.66417677 6.98462021 7.92511325]]


In [ ]:
A=np.floor(10*np.random.rand(8,4))
print(A)

[[8. 0. 2. 8.]
 [2. 4. 1. 5.]
 [6. 3. 2. 3.]
 [7. 8. 4. 6.]
 [9. 1. 9. 9.]
 [1. 7. 9. 9.]
 [7. 0. 8. 6.]
 [4. 9. 5. 3.]]


In [ ]:
A=np.arange(1,33).reshape(8,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
np.vsplit(A,4)# the spliting number should divide no of rows(8/4)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(A,(3,5)) #split it after 3rd row and 5th row

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
B=np.arange(1,33).reshape(4,8)
print(B)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(B,4)

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(B,(4,8))

[array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [17, 18, 19, 20],
        [25, 26, 27, 28]]),
 array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [29, 30, 31, 32]]),
 array([], shape=(4, 0), dtype=int64)]

In [ ]:
np.hsplit(B,(3,7))

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19],
        [25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]]),
 array([[ 8],
        [16],
        [24],
        [32]])]

In [ ]:
np.pi

3.141592653589793

In [ ]:
A=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
C=np.rad2deg(A) #convert radians into degrees
print(C)

[ 45.  60.  90. 180.]


In [ ]:
d=np.deg2rad(C)
print(d)


[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
np.sin(1)

0.8414709848078965

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.tan(1)

1.5574077246549023

In [ ]:
np.tan(np.pi/4)

0.9999999999999999

Statistics


In [ ]:
st=np.array([23,45,67,89,21,34])
np.mean(st)

46.5

In [ ]:
np.median(st)

39.5

In [ ]:
np.std(st) #std=sum of difference between observations/no.of observations

24.452334585202017

In [ ]:
np.var(st)

597.9166666666666

In [ ]:
C=np.arange(1,5).reshape(2,2)
print(C)

[[1 2]
 [3 4]]


In [ ]:
#inverse of matrix
np.linalg.inv(C)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
C=np.arange(1,25).reshape(6,4)
print(C)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
print(np.argmax(C))

23


In [ ]:
D=np.arange(1,33).reshape(8,4)
print(D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
C=np.floor(10*np.random.rand(24)).reshape(6,4)
print(C)

[[2. 1. 5. 9.]
 [6. 1. 3. 9.]
 [2. 1. 5. 5.]
 [3. 3. 6. 7.]
 [6. 1. 3. 7.]
 [8. 7. 8. 8.]]


In [ ]:
C=10*np.random.rand(24).reshape(6,4)
print(C)

[[2.05648795 5.39064127 7.69572902 7.13167671]
 [0.71126475 7.85049848 5.39469866 6.87805806]
 [1.72629071 8.35980624 6.84401895 4.81475885]
 [3.8103246  1.76977    8.40107338 4.46159545]
 [5.17739942 4.03949027 4.14167766 1.66955061]
 [3.91271276 9.50356945 8.61770002 8.75703693]]


In [ ]:
print(np.argmin(C))

4


In [ ]:
print(np.argmax(C))

21


In [ ]:
print(np.argmax(C,axis=0))

[4 5 5 5]


In [ ]:
print(np.argmax(C,axis=1))

[2 1 1 2 0 1]


In [ ]:
print(np.argmin(C,axis=0))

[1 3 4 4]


In [ ]:
print(np.argmin(C,axis=1))

[0 0 0 1 3 0]


searching

In [ ]:
a=np.array([34,56,7,17,88,91])
print(np.where(a%2==0)) #where condition is nothing but if

(array([0, 1, 4]),)


In [ ]:
print(np.where(a%2!=0))# for odd numbers

(array([2, 3, 5]),)


In [ ]:
b=np.array([24,16,7,17,54,60])
print(np.where(b%6==0))

(array([0, 4, 5]),)


In [ ]:
#for sorted array only
d=np.array([11,12,13,14,15])
x=np.searchsorted(d,14)
print(x)

3


In [ ]:
d=np.array([4,8,3,5,12])
x=np.searchsorted(d,4)
print(x)

3


In [ ]:
#sorting array
a=np.array(["banana","cherry","apple"])
print(np.sort(a))
b=np.array(["true","false","true"]) #false-0 #true-1
print(np.sort(b))

['apple' 'banana' 'cherry']
['false' 'true' 'true']


In [ ]:
#2D sort-sorting happens within row
a=np.array([[3,2,4],[5,0,1]])
print(np.sort(a))

[[2 3 4]
 [0 1 5]]


filter


In [ ]:
#filter
arr=np.array([40,43,50,44,67,78])
filt=np.where(arr%2==0)
print(filt)
arr[filt]

(array([0, 2, 3, 5]),)


array([40, 50, 44, 78])

In [ ]:
#iterting through two arrays
names=np.array(["jaya","divya","siva","reethi"])
initials=np.array(["k","l","s","v"])
for i,j in zip(initials,names): # do using list
  print(i,".",j)

k . jaya
l . divya
s . siva
v . reethi


In [ ]:
#multiplication of two arrays
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.multiply(a1,a2)
print(n)

[ 200  420  660  920 1200 1500]


In [ ]:
#division of two arrays
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.divide(a1,a2)
print(n)

[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [ ]:
#modulo operation between two arrays
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.mod(a1,a2)
print(n)

[10 20  8 17  2 10]


In [ ]:
#modulodivision between two arrays
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.divmod(a1,a2)
print(n)

(array([0, 0, 1, 1, 2, 2]), array([10, 20,  8, 17,  2, 10]))


In [ ]:
#logarithms
a=1.2
print(np.log10(a)) #log base 10

0.07918124604762482


In [ ]:
a=1.2
print(np.log(a)) #log e

0.1823215567939546


In [ ]:
a=np.array([1,1.2,3,4])
print(np.log(a))#natural log

[0.         0.18232156 1.09861229 1.38629436]


In [ ]:
#cummulative product
a=np.array([1,2,3,4,5])
x=np.cumprod(a)
print(x)

[  1   2   6  24 120]


In [ ]:
#cummulative sum
a=np.array([1,2,3,4,5])
x=np.cumsum(a)
print(x)

[ 1  3  6 10 15]


In [ ]:
#difference
a=np.array([1,3,5,7,9])
x=np.diff(a)
print(x)

[2 2 2 2]


In [ ]:
#LCM
n1=455
n2=665
x=np.lcm(n1,n2)
print(x)

8645


In [ ]:
#gcd
n1=455
n2=556
x=np.gcd(n1,n2)
print(x)

1


In [ ]:
a=np.array([5,25,50])
g=np.gcd.reduce(a) #takes multiple inputs gives single output
print(g)

5


In [ ]:
a=np.array([4,8,12,40])
g=np.lcm.reduce(a)
print(g)

[ 4  8 12 40]
